<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Adminhtml\Edit\Tab\View\PersonalInfo $block */
/** @var \Magento\Framework\Escaper $escaper */

$lastLoginDateAdmin = $block->getLastLoginDate();
$lastLoginDateStore = $block->getStoreLastLoginDate();

$createDateAdmin = $block->getCreateDate();
$createDateStore = $block->getStoreCreateDate();
$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];

// Omakazit_DisableCustomer Custom Code
/** @var \Omakazit\DisableCustomer\ViewModel\PersonalInfo $viewModel */
$viewModel = $block->getViewModel();
// /Omakazit_DisableCustomer Custom Code
?>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $escaper->escapeHtml(__('Personal Information')) ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?= $block->getChildHtml() ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Last Logged In:')) ?></th>
            <td><?= $escaper->escapeHtml($lastLoginDateAdmin) ?> (<?= $escaper->escapeHtml($block->getCurrentStatus()) ?>)</td>
        </tr>
        <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Last Logged In (%1):', $block->getStoreLastLoginDateTimezone())) ?></th>
            <td><?= $escaper->escapeHtml($lastLoginDateStore) ?> (<?= $escaper->escapeHtml($block->getCurrentStatus()) ?>)</td>
        </tr>
        <?php endif; ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Account Lock:')) ?></th>
            <td><?= $escaper->escapeHtml($block->getAccountLock()) ?></td>
        </tr>

        <?php // Omakazit_DisableCustomer Custom Code ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Account Disabled:')) ?></th>
            <td><?= $escaper->escapeHtml(__($viewModel->getDisableStatus($block->getCustomer()))) ?></td>
        </tr>
        <?php // /Omakazit_DisableCustomer Custom Code ?>

        <tr>
            <th><?= $escaper->escapeHtml(__('Confirmed email:')) ?></th>
            <td><?= $escaper->escapeHtml($block->getIsConfirmedStatus()) ?></td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Account Created:')) ?></th>
            <td><?= $escaper->escapeHtml($createDateAdmin) ?></td>
        </tr>
        <?php if ($createDateAdmin != $createDateStore): ?>
            <tr>
                <th><?= $escaper->escapeHtml(__('Account Created on (%1):', $block->getStoreCreateDateTimezone())) ?></th>
                <td><?= $escaper->escapeHtml($createDateStore) ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Account Created in:')) ?></th>
            <td><?= $escaper->escapeHtml($block->getCreatedInStore()) ?></td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Customer Group:')) ?></th>
            <td><?= $escaper->escapeHtml($block->getGroupName()) ?></td>
        </tr>
        </tbody>
    </table>
    <address>
        <strong><?= $escaper->escapeHtml(__('Default Billing Address')) ?></strong><br/>
        <?= $escaper->escapeHtml($block->getBillingAddressHtml(), $allowedAddressHtmlTags) ?>
    </address>

</div>
